name: Build and Release Python Package

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Check version
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      run: |
        echo "TAG_VERSION=$(echo $GITHUB_REF | sed 's#.*/v##')" >> $GITHUB_ENV
        echo "PACKAGE_VERSION=$(python setup.py --version)" >> $GITHUB_ENV
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        path: ./dist/*
    outputs:
      tag_version: ${{ env.TAG_VERSION }}
      package_version: ${{ env.PACKAGE_VERSION }}


  release:
    runs-on: ubuntu-latest
    needs: [build]
    environment: release
    permissions:
      id-token: write
      contents: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && needs.build.outputs.tag_version == needs.build.outputs.package_version
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        path: ./dist/
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/*
        generate_release_notes: True
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
